import React from 'react';
import { Link } from 'react-router-dom';
import { Award, Clock, ArrowRight } from 'lucide-react';

export const AssessmentsPage: React.FC = () => {
  const assessments = [
    {
      id: 'google-l4',
      company: 'Google',
      title: 'Google L4 Software Engineer Loop',
      logo: '🌐',
      color: 'border-blue-500/30 bg-blue-500/5',
      badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
      duration: '75 Mins',
      problemsCount: 3,
      difficulty: 'Hard / Medium',
      description: 'Simulates the official 75-minute Google onsite coding evaluation covering Dynamic Programming, Graph Traversal, and Space Optimization.'
    },
    {
      id: 'meta-e4',
      company: 'Meta',
      title: 'Meta E4 Online Coding Assessment',
      logo: '♾️',
      color: 'border-purple-500/30 bg-purple-500/5',
      badgeColor: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
      duration: '60 Mins',
      problemsCount: 2,
      difficulty: 'Medium / Medium',
      description: 'High-speed 60-minute Meta interview simulation testing Binary Trees, Two-Pointers, and String Parsing accuracy under pressure.'
    },
    {
      id: 'amazon-sde2',
      company: 'Amazon',
      title: 'Amazon SDE-2 Online Evaluation',
      logo: '📦',
      color: 'border-amber-500/30 bg-amber-500/5',
      badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
      duration: '90 Mins',
      problemsCount: 2,
      difficulty: 'Hard / Hard',
      description: 'Rigorous Amazon SDE-2 technical assessment testing Heap Priority Queues, LRU Cache design, and Leadership Principles.'
    }
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-28 pb-16 space-y-8 text-left">
      <div className="space-y-2">
        <div className="inline-flex items-center gap-2 text-xs font-bold text-amber-500 uppercase tracking-wider font-mono">
          <Award className="w-4 h-4" />
          OFFICIAL FAANG MOCK INTERVIEW EVALUATOR
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-neutral-950 dark:text-white tracking-tight">
          FAANG Timed Coding Assessments
        </h1>
        <p className="text-sm text-neutral-500 max-w-2xl">
          Test your coding speed and algorithmic accuracy in full-screen timed interview loops generated by real FAANG interview rubrics.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {assessments.map(a => (
          <div key={a.id} className={`p-6 rounded-3xl border ${a.color} space-y-5 flex flex-col justify-between shadow-xs transition-all hover:scale-101`}>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-3xl">{a.logo}</span>
                <span className={`px-3 py-1 rounded-full text-xs font-extrabold font-mono border ${a.badgeColor}`}>
                  {a.company}
                </span>
              </div>

              <div className="space-y-1">
                <h3 className="text-lg font-extrabold text-neutral-950 dark:text-white">{a.title}</h3>
                <p className="text-xs text-neutral-500 leading-relaxed">{a.description}</p>
              </div>

              <div className="pt-2 grid grid-cols-2 gap-2 text-xs font-mono">
                <div className="p-2.5 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 text-neutral-800 dark:text-neutral-200">
                  <div className="text-[10px] text-neutral-400 font-sans uppercase">Time Limit</div>
                  <div className="font-bold text-amber-500 flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" /> {a.duration}
                  </div>
                </div>

                <div className="p-2.5 rounded-xl bg-white dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 text-neutral-800 dark:text-neutral-200">
                  <div className="text-[10px] text-neutral-400 font-sans uppercase">Problems</div>
                  <div className="font-bold text-neutral-900 dark:text-white">
                    {a.problemsCount} Questions
                  </div>
                </div>
              </div>
            </div>

            <Link
              to="/problems/1"
              className="w-full py-3 rounded-2xl bg-neutral-950 hover:bg-neutral-800 dark:bg-white dark:hover:bg-neutral-100 text-white dark:text-neutral-950 font-extrabold text-xs shadow-md transition-all flex items-center justify-center gap-2"
            >
              <span>Begin Timed Assessment</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};
